# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd80f578f23305b311453dc4ce6142dbc39c18f1b3b7905ac4aa0cb0a731a0267a94e8e2b1a8dd1f666c552022c64a8d9d349507c3124c38cdbf05e1b7765084

test:
  secret_key_base: 57e837f1f93e58161e956bcb85e68bdce2679ca3d7fa0875b7c5c275ddb3a350ea65f77ef4c9ff3965b73a7308f6b66e55628dcdf425aa892308a985af7aeb38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
